version: "3.7"

volumes:
  db1:
    driver: local

services:
  db1:
    container_name: db1
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: db1-pwd
      TZ: Asia/Jakarta
    volumes:
      - db1:/var/lib/mysql
    networks:
      - cais-nginx-network # proxy and app must be in same network

  phpmyadmin1:
    container_name: app1
    depends_on:
      - db1
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db1
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=/app1/
    networks:
      - cais-nginx-network # proxy and app must be in same network
      - app1-network # you can use additional networks for some stuff

networks:
  cais-nginx-network:
    external: true
  app1-network: ~ # this network won't be accessible from outside